version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always

    volumes:
      - ./mongo:/data/db

    ports:
      - "27017:27017"

    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always

    ports:
      - "6379:6379"

    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    external: false
