debug = true
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "qitup.ca"
watch = true
exposedbydefault = false

[acme]
email = "trevorfoster19@gmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
dnsProvider = "route53"
OnHostRule = true
delayDontCheckDNS = 0

[[acme.domains]]
  main = "qitup.ca"
  sans = ["api.qitup.ca"]

# Enable web backend
[web]
address = ":8080"
