---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
    - "recipe[apt]"
    - "recipe[queueitup]"
    attributes: {}
